# Anna KaRNNa

In this notebook, we'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

![1.png](c:/Users/zhangwenqi/Desktop/1.png)

In [1]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

## 建立单词表

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.
载入文本,建立单词表和单词表索引

In [2]:
with open(r'F:\uav+ai\神经网络test\第三课循环神经网络\3LSTM长短记忆单元\intro-to-rnns\anna.txt', 'r') as f:
    text=f.read()
vocab = sorted(set(text))# 采用set集合建立单词表  存有abcd-z的字母表
vocab_to_int = {c: i for i, c in enumerate(vocab)} #为单词表建立序号 
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)#按照单词表索引，对应每个字母建立编码

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [4]:
encoded[:100]

array([31, 64, 57, 72, 76, 61, 74,  1, 16,  0,  0,  0, 36, 57, 72, 72, 81,
        1, 62, 57, 69, 65, 68, 65, 61, 75,  1, 57, 74, 61,  1, 57, 68, 68,
        1, 57, 68, 65, 67, 61, 26,  1, 61, 78, 61, 74, 81,  1, 77, 70, 64,
       57, 72, 72, 81,  1, 62, 57, 69, 65, 68, 81,  1, 65, 75,  1, 77, 70,
       64, 57, 72, 72, 81,  1, 65, 70,  1, 65, 76, 75,  1, 71, 79, 70,  0,
       79, 57, 81, 13,  0,  0, 33, 78, 61, 74, 81, 76, 64, 65, 70])

In [5]:
len(encoded)

1985223

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [6]:
len(vocab)

83

## Making training mini-batches 1、创建迭代器形成批次数据2、将一维数据改成二维

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>

We start with our text encoded as integers in one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator. 创建一个迭代器来实现批次出序列数据

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the total number of batches, $K$, we can make from the array `arr`, you divide the length of `arr` by the number of characters per batch. Once you know the number of batches, you can get the total number of characters to keep from `arr`, $N * M * K$.  N代表批次分割数，即转化为二维数组的size大小，M代表每个batch的行元素，k代表总的步数，即batch数

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`batch_size` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the $N \times (M * K)$ array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. 输出序列是输入序列的时序下一个平移，输入序列是以n_step间隔取，即输入是n*m

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

> **Exercise:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [7]:
def get_batches(arr, batch_size, n_steps):  #创造迭代器，对文本序列形成批次分割和迭代，可以调用next得到下批次的序列文本编码
    # x代表当前输入 y代表下一个序列输入的序列，即也是标签值
    '''Create a generator that returns batches of size
       batch_size x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       batch_size: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the number of characters per batch and number of batches we can make
    chars_per_batch = batch_size * n_steps#相当于N*M 10*50
    n_batches = len(arr)//chars_per_batch  #1985223/50=39704
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * chars_per_batch]#取整数个数，统一格式 39704*500=1985200
    
    # Reshape into batch_size rows
    arr = arr.reshape((batch_size, -1))#把arr序列变成了二维数组 为10*198520
    
    for n in range(0, arr.shape[1], n_steps):#range(0,198520,50)即每隔50个步长取，最后形成10*50的x输出序列，共198520/50个batch
        # The features
        x = arr[:, n:n+n_steps] #x是10*50的二维数组
        # The targets, shifted by one
        y_temp = arr[:, n+1:n+n_steps+1] #y比x时序上往后推一步，这样算y数组会少一个元素，需要补齐
        
        # For the very last batch, y will be one character short at the end of 
        # the sequences which breaks things. To get around this, I'll make an 
        # array of the appropriate size first, of all zeros, then add the targets.
        # This will introduce a small artifact in the last batch, but it won't matter.
        y = np.zeros(x.shape, dtype=x.dtype)
        y[:,:y_temp.shape[1]] = y_temp
        
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [8]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)
print('x\n', x[:10, :50])  #x是10行50列的二维列表  ，即每行50个元素组成，
print('\ny\n', y[:10, :50])

x
 [[31 64 57 72 76 61 74  1 16  0  0  0 36 57 72 72 81  1 62 57 69 65 68 65
  61 75  1 57 74 61  1 57 68 68  1 57 68 65 67 61 26  1 61 78 61 74 81  1
  77 70]
 [ 1 57 69  1 70 71 76  1 63 71 65 70 63  1 76 71  1 75 76 57 81 11  3  1
  57 70 75 79 61 74 61 60  1 29 70 70 57 11  1 75 69 65 68 65 70 63 11  1
  58 77]
 [78 65 70 13  0  0  3 53 61 75 11  1 65 76  7 75  1 75 61 76 76 68 61 60
  13  1 48 64 61  1 72 74 65 59 61  1 65 75  1 69 57 63 70 65 62 65 59 61
  70 76]
 [70  1 60 77 74 65 70 63  1 64 65 75  1 59 71 70 78 61 74 75 57 76 65 71
  70  1 79 65 76 64  1 64 65 75  0 58 74 71 76 64 61 74  1 79 57 75  1 76
  64 65]
 [ 1 65 76  1 65 75 11  1 75 65 74  2  3  1 75 57 65 60  1 76 64 61  1 71
  68 60  1 69 57 70 11  1 63 61 76 76 65 70 63  1 77 72 11  1 57 70 60  0
  59 74]
 [ 1 37 76  1 79 57 75  0 71 70 68 81  1 79 64 61 70  1 76 64 61  1 75 57
  69 61  1 61 78 61 70 65 70 63  1 64 61  1 59 57 69 61  1 76 71  1 76 64
  61 65]
 [64 61 70  1 59 71 69 61  1 62 71 74  1 69 61 11  3  1

In [9]:
np.shape(x)

(10, 50)

In [10]:
x, y = next(batches) #迭代器采用yield 关键字，采用next调用获取下一个迭代结果
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[64 57 72 72 81  1 62 57 69 65]
 [76  1 65 70  1 75 72 65 76 61]
 [26  1 76 64 65 74 76 81 12 61]
 [75 13  1 43 70 59 61  1 65 70]
 [71 75 75 65 70 63  1 64 65 69]
 [74  1 64 71 77 75 61  1 58 61]
 [ 1 74 71 71 69 13  0  0 40 61]
 [61 74 61 68 81  0 75 77 59 64]
 [76 64 61  1 68 57 70 60 71 79]
 [70 63 13  1  3 36 61  7 75  1]]

y
 [[57 72 72 81  1 62 57 69 65 68]
 [ 1 65 70  1 75 72 65 76 61  1]
 [ 1 76 64 65 74 76 81 12 61 65]
 [13  1 43 70 59 61  1 65 70  1]
 [75 75 65 70 63  1 64 65 69 75]
 [ 1 64 71 77 75 61  1 58 61 62]
 [74 71 71 69 13  0  0 40 61 78]
 [74 61 68 81  0 75 77 59 64  1]
 [64 61  1 68 57 70 60 71 79 70]
 [63 13  1  3 36 61  7 75  1 76]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model  创建rnn输入模型

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="F:/uav+ai/神经网络test/第三课循环神经网络/3LSTM长短记忆单元/intro-to-rnns/assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`. This will be a scalar, that is a 0-D tensor. To make a scalar, you create a placeholder without giving it a size.

> **Exercise:** Create the input placeholders in the function below.

In [11]:
def build_inputs(batch_size, num_steps): #输入序列是n*m的矩阵
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph  体现了二维输入序列
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. Previously with TensorFlow 1.0, you could do this

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)#形成堆叠的rnn单元
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow 1.0 will create different weight matrices for all `cell` objects. But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like

```python
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop
    
tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
```

Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

### 建立多层LSTM

In [12]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    
    def build_cell(lstm_size, keep_prob):
        # Use a basic LSTM cell
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)#LSTM的维度lstm_size
        
        # Add dropout to the cell
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
    
    
    # Stack up multiple LSTM layers, for deep learning  创造多层LSTM
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character, so we want this layer to have size $C$, the number of classes/characters we have in our text.  
1、LSTM后面接全连接层，全连接层是softmax的输出，即单词表的各字母的预测概率  
If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$.   
2、 batch_size大小是N，time_step大小是M，lstm_size大小是L，即隐层单元维度是L，则输出是$N \times M \times L$

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells. We get the LSTM output as a list, `lstm_output`. First we need to concatenate this whole list into one array with [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat). Then, reshape it (with `tf.reshape`) to size $(M * N) \times L$.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

> **Exercise:** Implement the output layer in the function below.

In [13]:
def build_output(lstm_output, in_size, out_size): #in_size为LSTM_size  而out_size为num_class即84
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        x: Input tensor
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # That is, the shape should be batch_size*num_steps rows by lstm_size columns
    print(np.shape((lstm_output)),'np.shape((lstm_output))')    #（64,50,128）
    seq_output = tf.concat(lstm_output, axis=1)#lstm_output是一个batch_size * time_steps * LSTM_sizes维度 64*50*128维度
    print(np.shape(seq_output),'np.shape(seq_output)')      
    x = tf.reshape(seq_output, [-1, in_size])# 降维降成3200*128
    print(np.shape(x),'np.shape(x)') #（3200,128）
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))#128*84 的二维
        softmax_b = tf.Variable(tf.zeros(out_size))  #84
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b  #x是3200*128 而w是128*84 =3200*84
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    print(np.shape(out),'np.shape(out)') #3200*84
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

>**Exercise:** Implement the loss calculation in the function below.

In [14]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per batch_size per step
    y_one_hot = tf.one_hot(targets, num_classes)#targets 是64*50维度 经过one_hot编码后增加了一个维度 64*50*84
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())#logits.get_shape()是（3200,84），则y_reshaped也变reshape成3200*84
    print(np.shape(y_reshaped),'np.shape(y_reshaped)')
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    return loss

### Optimizer
lstm解决了梯度消失里的问题，但是针对梯度爆炸问题，采用截断梯度的办法实现
Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [15]:
def build_optimizer(loss, learning_rate, grad_clip):#采用截断梯度办法防止梯度爆炸
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

> **Exercise:** Use the functions you've implemented previously and `tf.nn.dynamic_rnn` to build the network.

In [16]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False): #代表有两层LSTM，每层LSTM里面隐藏层节点数是128，time_steps=50
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)
        #通过build_inputs建立输入映射，self.inputs是64*50，self.targets是64*50
        
        
        # Build the LSTM cell 建立LSTM单元
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)
        # 通过建立LSTM单元，cell是2层LSTM，每层LSTM是128个隐节点 ，每个隐节点都带有dropout
        
        
        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)#对输入序列64*50进行热独编码 64*50*84
        print(np.shape(x_one_hot),'np.shape(x_one_hot)')
        
        
        # Run each sequence step through the RNN and collect the outputs
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)#outputs是64*50*128
        self.final_state = state
        #通过dynamic_rnn得到的是64*50*128维度,相当于这里是将84个输入点变成128个隐节点，并且有4个控制门，总权重数为84*128*4
        
        # Get softmax predictions and logits  #这里将lstm的输出连接输出层即sortmax进行分类
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        #其中outputs是64*50*128维度，而经过reshape成3200*128然后再通过权重矩阵（128,84），最后输出是3200*84
        # Loss and optimizer (with gradient clipping)
        
        
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters 超参数的调整

Here are the hyperparameters for the network.

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks 

>### Monitoring Validation Loss vs. Training Loss  观察验证集和训练集的损失，调整dropout来缓解过拟合问题
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters 两个比较重要的参数是lstm_size和num_layers，即代表每个隐层的单元数和隐层数,该两个参数决定了需要训练的权重和偏置的总参数数量

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.
 ## 参数的数量取决于样本的大小，经验公式 1MB的数据样本 大概  采用1million 个权重参数

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

In [17]:
batch_size = 10         # Sequences per batch
num_steps = 50          # Number of sequence steps per batch
lstm_size = 128         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.01    # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

> **Exercise:** Set the hyperparameters above to train the network. Watch the training loss, it should be consistently dropping. Also, I highly advise running this on a GPU.

In [18]:
epochs = 20
# Print losses every N interations
print_every_n = 50

# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            #在batch分批次计算中，每次生成的final_state保存为new_state，然后下一批次将new_state传入feed继续计算
            if (counter % print_every_n == 0):
                end = time.time()
                print('Epoch: {}/{}... '.format(e+1, epochs),
                      'Training Step: {}... '.format(counter),
                      'Training loss: {:.4f}... '.format(batch_loss),
                      '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Instructions for updating:
Use the retry module or similar alternatives.
(10, 50, 83) np.shape(x_one_hot)
(10, 50, 128) np.shape((lstm_output))
(10, 50, 128) np.shape(seq_output)
(500, 128) np.shape(x)
(500, 83) np.shape(out)
(500, 83) np.shape(y_reshaped)
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

Epoch: 1/20...  Training Step: 50...  Training loss: 3.1397...  0.1000 sec/batch
Epoch: 1/20...  Training Step: 100...  Training loss: 2.6794...  0.0960 sec/batch
Epoch: 1/20...  Training Step: 150...  Training loss: 2.4449...  0.0960 sec/batch
Epoch: 1/20...  Training Step: 200...  Training loss: 2.4993...  0.0990 sec/batch
Epoch: 1/20...  Training Step: 250...  Training loss: 2.4008...  0.1090 sec/batch
Epoch: 1/20...  Training Step: 300...  Training loss: 2.2039...  0.1000 sec/batch
Epoch: 1/20...  Training Step: 350...  Training loss: 2.1796...

Epoch: 2/20...  Training Step: 4450...  Training loss: 1.7921...  0.1120 sec/batch
Epoch: 2/20...  Training Step: 4500...  Training loss: 1.7472...  0.1180 sec/batch
Epoch: 2/20...  Training Step: 4550...  Training loss: 1.9029...  0.1060 sec/batch
Epoch: 2/20...  Training Step: 4600...  Training loss: 1.7738...  0.1250 sec/batch
Epoch: 2/20...  Training Step: 4650...  Training loss: 1.8598...  0.1180 sec/batch
Epoch: 2/20...  Training Step: 4700...  Training loss: 1.5767...  0.1180 sec/batch
Epoch: 2/20...  Training Step: 4750...  Training loss: 1.7852...  0.1220 sec/batch
Epoch: 2/20...  Training Step: 4800...  Training loss: 1.6019...  0.1190 sec/batch
Epoch: 2/20...  Training Step: 4850...  Training loss: 1.6127...  0.1150 sec/batch
Epoch: 2/20...  Training Step: 4900...  Training loss: 1.7012...  0.1110 sec/batch
Epoch: 2/20...  Training Step: 4950...  Training loss: 1.5946...  0.1200 sec/batch
Epoch: 2/20...  Training Step: 5000...  Training loss: 1.7323...  0.1210 sec/batch
Epoc

Epoch: 3/20...  Training Step: 9400...  Training loss: 1.7073...  0.1200 sec/batch
Epoch: 3/20...  Training Step: 9450...  Training loss: 1.5471...  0.1160 sec/batch
Epoch: 3/20...  Training Step: 9500...  Training loss: 1.7109...  0.1220 sec/batch
Epoch: 3/20...  Training Step: 9550...  Training loss: 1.7326...  0.1200 sec/batch
Epoch: 3/20...  Training Step: 9600...  Training loss: 1.5398...  0.1230 sec/batch
Epoch: 3/20...  Training Step: 9650...  Training loss: 1.5698...  0.1170 sec/batch
Epoch: 3/20...  Training Step: 9700...  Training loss: 1.5436...  0.1140 sec/batch
Epoch: 3/20...  Training Step: 9750...  Training loss: 1.4101...  0.1120 sec/batch
Epoch: 3/20...  Training Step: 9800...  Training loss: 1.6785...  0.1180 sec/batch
Epoch: 3/20...  Training Step: 9850...  Training loss: 1.5486...  0.1200 sec/batch
Epoch: 3/20...  Training Step: 9900...  Training loss: 1.6763...  0.1460 sec/batch
Epoch: 3/20...  Training Step: 9950...  Training loss: 1.7032...  0.1220 sec/batch
Epoc

KeyboardInterrupt: 

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [36]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints\\i12400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i600_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i800_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1000_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1600_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1800_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2000_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2600_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2800_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i3000_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i3200_l128.ckpt"
all_m

## Sampling  模仿作者写文本
### 输入一个字符串，采用模型预测下一个，然后将预测的结果再次输入，迭代预测生成文本
Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [19]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [33]:
xx = np.zeros((1, 1))
xx

array([[0.]])

In [56]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    print(prime,'prime:')
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:#将prime的字符串中的字符t，h，e先输入模型，然后开始预测第四个字符，当输入的字符越多，模型输出的文本越像作者
            x = np.zeros((1, 1))
            print('c:',c)
            x[0,0] = vocab_to_int[c]
            print('x:',x)
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)
        print('preds：',preds)
        c = pick_top_n(preds, len(vocab))
        print('c:',c)
        samples.append(int_to_vocab[c])
        print('sample：',samples)
        
        for i in range(n_samples):
            x[0,0] = c

            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [57]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints\\i8800_l128.ckpt'

In [62]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 200, lstm_size, len(vocab), prime="wif")
print(samp)

(1, 1, 83) np.shape(x_one_hot)
(1, 1, 128) np.shape((lstm_output))
(1, 1, 128) np.shape(seq_output)
(1, 128) np.shape(x)
(1, 83) np.shape(out)
(1, 83) np.shape(y_reshaped)
wif prime:
INFO:tensorflow:Restoring parameters from checkpoints\i8800_l128.ckpt
c: w
x: [[79.]]
c: i
x: [[65.]]
c: f
x: [[62.]]
preds： [[6.99375914e-06 2.64007802e-04 2.85105170e-06 2.97230166e-12
  2.88701420e-12 4.02556851e-12 1.58542699e-12 6.45307455e-06
  2.46013418e-11 9.66278790e-08 3.76786005e-13 2.31896429e-05
  2.98001225e-07 9.99418353e-06 4.71003011e-12 1.43471305e-14
  7.45509950e-15 2.95208329e-14 1.46274162e-15 1.51079930e-14
  3.09254135e-14 1.13291463e-13 1.14361738e-14 2.21426610e-14
  2.51134400e-13 8.60028422e-07 1.27167129e-06 2.53626627e-06
  1.02251289e-11 9.64347768e-11 3.84747139e-12 1.39485201e-09
  6.35971692e-11 2.13927862e-10 2.85082266e-12 7.56942252e-12
  1.02307811e-12 8.22072662e-13 2.06214750e-11 4.55440243e-12
  1.07494976e-11 1.24574170e-11 7.08498321e-12 1.45348915e-11
  2.770606