# 生成电视剧剧本

在这个项目中，你将使用 RNN 创作你自己的[《辛普森一家》](https://zh.wikipedia.org/wiki/%E8%BE%9B%E6%99%AE%E6%A3%AE%E4%B8%80%E5%AE%B6)电视剧剧本。你将会用到《辛普森一家》第 27 季中部分剧本的[数据集](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data)。你创建的神经网络将为一个在 [Moe 酒馆](https://simpsonswiki.com/wiki/Moe's_Tavern)中的场景生成一集新的剧本。
## 获取数据
我们早已为你提供了数据。你将使用原始数据集的子集，它只包括 Moe 酒馆中的场景。数据中并不包括酒馆的其他版本，比如 “Moe 的山洞”、“燃烧的 Moe 酒馆”、“Moe 叔叔的家庭大餐”等等。

In [1]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper

data_dir = r'F:\uav+ai\神经网络test\第三课循环神经网络\7生成电视剧本\tv-script-generation\data\simpsons/moes_tavern_lines.txt'
text = helper.load_data(data_dir)
# Ignore notice, since we don't use it for analysing the data
text = text[80:]

In [2]:
text

'\nMoe_Szyslak: (INTO PHONE) Moe\'s Tavern. Where the elite meet to drink.\nBart_Simpson: Eh, yeah, hello, is Mike there? Last name, Rotch.\nMoe_Szyslak: (INTO PHONE) Hold on, I\'ll check. (TO BARFLIES) Mike Rotch. Mike Rotch. Hey, has anybody seen Mike Rotch, lately?\nMoe_Szyslak: (INTO PHONE) Listen you little puke. One of these days I\'m gonna catch you, and I\'m gonna carve my name on your back with an ice pick.\nMoe_Szyslak: What\'s the matter Homer? You\'re not your normal effervescent self.\nHomer_Simpson: I got my problems, Moe. Give me another one.\nMoe_Szyslak: Homer, hey, you should not drink to forget your problems.\nBarney_Gumble: Yeah, you should only drink to enhance your social skills.\n\n\nMoe_Szyslak: Ah, isn\'t that nice. Now, there is a politician who cares.\nBarney_Gumble: If I ever vote, it\'ll be for him. (BELCH)\n\n\nBarney_Gumble: Hey Homer, how\'s your neighbor\'s store doing?\nHomer_Simpson: Lousy. He just sits there all day. He\'d have a great job if he didn

## 探索数据
使用 `view_sentence_range` 来查看数据的不同部分。

In [3]:
view_sentence_range = (0, 10)

"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import numpy as np

print('Dataset Stats')
print('Roughly the number of unique words: {}'.format(len({word: None for word in text.split()})))# 获取单词表的单词数
scenes = text.split('\n\n')#list里存字符串，每个场景的所有台词为一个字符串
print('Number of scenes: {}'.format(len(scenes)))#剧本的场景数  即两个换行符
sentence_count_scene = [scene.count('\n') for scene in scenes]# 每个场景的台词行数
print('Average number of sentences in each scene: {}'.format(np.average(sentence_count_scene)))#每个场景的台词数

sentences = [sentence for scene in scenes for sentence in scene.split('\n')]#总台词，一行台词一个字符串， 包括一些空字符，由于换行符造成
print('Number of lines: {}'.format(len(sentences)))
word_count_sentence = [len(sentence.split()) for sentence in sentences]#每句台词的单词数
print('Average number of words in each line: {}'.format(np.average(word_count_sentence)))

print()
print('The sentences {} to {}:'.format(*view_sentence_range))
print('\n'.join(text.split('\n')[view_sentence_range[0]:view_sentence_range[1]]))

Dataset Stats
Roughly the number of unique words: 11492
Number of scenes: 262
Average number of sentences in each scene: 15.251908396946565
Number of lines: 4258
Average number of words in each line: 11.50164396430249

The sentences 0 to 10:

Moe_Szyslak: (INTO PHONE) Moe's Tavern. Where the elite meet to drink.
Bart_Simpson: Eh, yeah, hello, is Mike there? Last name, Rotch.
Moe_Szyslak: (INTO PHONE) Hold on, I'll check. (TO BARFLIES) Mike Rotch. Mike Rotch. Hey, has anybody seen Mike Rotch, lately?
Moe_Szyslak: (INTO PHONE) Listen you little puke. One of these days I'm gonna catch you, and I'm gonna carve my name on your back with an ice pick.
Moe_Szyslak: What's the matter Homer? You're not your normal effervescent self.
Homer_Simpson: I got my problems, Moe. Give me another one.
Moe_Szyslak: Homer, hey, you should not drink to forget your problems.
Barney_Gumble: Yeah, you should only drink to enhance your social skills.



In [4]:
word_count_sentence

[0,
 11,
 10,
 20,
 28,
 11,
 10,
 11,
 11,
 0,
 12,
 10,
 0,
 8,
 20,
 11,
 5,
 3,
 0,
 7,
 11,
 22,
 37,
 17,
 9,
 9,
 2,
 17,
 22,
 12,
 32,
 4,
 7,
 2,
 11,
 0,
 13,
 37,
 6,
 5,
 0,
 14,
 7,
 11,
 3,
 16,
 3,
 11,
 6,
 7,
 8,
 7,
 8,
 8,
 26,
 25,
 16,
 10,
 9,
 9,
 8,
 4,
 0,
 6,
 4,
 5,
 32,
 9,
 17,
 6,
 4,
 9,
 27,
 15,
 15,
 8,
 16,
 3,
 14,
 4,
 13,
 8,
 9,
 12,
 5,
 6,
 6,
 15,
 12,
 8,
 17,
 6,
 40,
 4,
 4,
 5,
 5,
 31,
 10,
 10,
 11,
 8,
 11,
 6,
 19,
 10,
 14,
 11,
 12,
 3,
 7,
 9,
 8,
 5,
 4,
 13,
 5,
 7,
 19,
 9,
 15,
 14,
 13,
 3,
 18,
 24,
 17,
 12,
 10,
 13,
 9,
 17,
 11,
 15,
 4,
 9,
 13,
 10,
 4,
 0,
 14,
 5,
 13,
 38,
 5,
 41,
 8,
 10,
 17,
 19,
 18,
 19,
 4,
 14,
 7,
 14,
 25,
 4,
 9,
 25,
 7,
 8,
 13,
 6,
 10,
 22,
 11,
 20,
 8,
 50,
 7,
 15,
 20,
 9,
 7,
 13,
 16,
 17,
 2,
 22,
 4,
 9,
 5,
 20,
 4,
 10,
 11,
 7,
 8,
 7,
 10,
 12,
 22,
 22,
 0,
 10,
 10,
 23,
 13,
 6,
 11,
 9,
 15,
 27,
 7,
 5,
 11,
 7,
 10,
 20,
 4,
 11,
 9,
 15,
 14,
 10,
 4,
 13,
 17,
 8,
 1

## 实现预处理函数
对数据集进行的第一个操作是预处理。请实现下面两个预处理函数：

- 查询表
- 标记符号的字符串 

### 查询表  --针对字母的查询表
要创建词嵌入，你首先要将单词转换为 id。请在这个函数中创建两个字典：

- 将词语转换为 id 的字典，我们称它为 `vocab_to_int`
- 将 id 转换为词语的字典，我们称它为 `int_to_vocab`

请在下面的元组中返回这些字典
 `(vocab_to_int, int_to_vocab)`

In [35]:
import numpy as np
import problem_unittests as tests
from string import punctuation

def create_lookup_tables(text):
    """
    Create lookup tables for vocabulary
    :param text: The text of tv scripts split into words
    :return: A tuple of dicts (vocab_to_int, int_to_vocab)
    """
    vocab_to_int = {w:i for i, w in enumerate(set(text))}
    int_to_vocab = {i:w for i, w in enumerate(set(text))}
     
    return (vocab_to_int, int_to_vocab)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_create_lookup_tables(create_lookup_tables)

Tests Passed


In [40]:
(vocab_to_int, int_to_vocab)=create_lookup_tables(text)

In [41]:
vocab_to_int

{'\n': 40,
 ' ': 59,
 '!': 29,
 '"': 80,
 '#': 19,
 '$': 32,
 '%': 33,
 '&': 87,
 "'": 82,
 '(': 3,
 ')': 62,
 ',': 26,
 '-': 23,
 '.': 76,
 '/': 1,
 '0': 13,
 '1': 64,
 '2': 72,
 '3': 78,
 '4': 14,
 '5': 16,
 '6': 57,
 '7': 25,
 '8': 86,
 '9': 17,
 ':': 73,
 ';': 20,
 '?': 10,
 'A': 63,
 'B': 70,
 'C': 67,
 'D': 31,
 'E': 12,
 'F': 28,
 'G': 68,
 'H': 21,
 'I': 24,
 'J': 18,
 'K': 61,
 'L': 43,
 'M': 30,
 'N': 0,
 'O': 11,
 'P': 41,
 'Q': 55,
 'R': 6,
 'S': 49,
 'T': 44,
 'U': 7,
 'V': 22,
 'W': 54,
 'X': 36,
 'Y': 9,
 'Z': 88,
 '_': 27,
 'a': 53,
 'b': 48,
 'c': 51,
 'd': 37,
 'e': 52,
 'f': 50,
 'g': 42,
 'h': 46,
 'i': 83,
 'j': 4,
 'k': 66,
 'l': 56,
 'm': 38,
 'n': 60,
 'o': 47,
 'p': 69,
 'q': 15,
 'r': 34,
 's': 35,
 't': 5,
 'u': 2,
 'v': 65,
 'w': 58,
 'x': 71,
 'y': 84,
 'z': 75,
 '猫': 85,
 '盲': 81,
 '眉': 74,
 '脌': 8,
 '脿': 79,
 '茅': 77,
 '茫': 45,
 '贸': 39}

### 标记符号的字符串  该部分创造一个dict，将标点符号统一成||标点符号名称||
我们会使用空格当作分隔符，来将剧本分割为词语数组。然而，句号和感叹号等符号使得神经网络难以分辨“再见”和“再见！”之间的区别。

实现函数 `token_lookup` 来返回一个字典，这个字典用于将 “!” 等符号标记为 “||Exclamation_Mark||” 形式。为下列符号创建一个字典，其中符号为标志，值为标记。

- period ( . )
- comma ( , )
- quotation mark ( " )
- semicolon ( ; )
- exclamation mark ( ! )
- question mark ( ? )
- left parenthesis ( ( )
- right parenthesis ( ) )
- dash ( -- )
- return ( \n )

这个字典将用于标记符号并在其周围添加分隔符（空格）。这能将符号视作单独词汇分割开来，并使神经网络更轻松地预测下一个词汇。请确保你并没有使用容易与词汇混淆的标记。与其使用 “dash” 这样的标记，试试使用“||dash||”。

In [6]:
def token_lookup():
    """
    Generate a dict to turn punctuation into a token.
    :return: Tokenize dictionary where the key is the punctuation and the value is the token
    """
    return {
        '.': '||Period||',
        ',': '||Comma||',
        '"': '||Quotation_Mark||',
        ';': '||Semicolon||',
        '!': '||Exclamation_mark||',
        '?': '||Question_mark||',
        '(': '||Left_Parentheses||',
        ')': '||Right_Parentheses||',
        '--': '||Dash||',
        "\n": '||Return||'
    }

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_tokenize(token_lookup)

Tests Passed


In [7]:
token_lookup()

{'\n': '||Return||',
 '!': '||Exclamation_mark||',
 '"': '||Quotation_Mark||',
 '(': '||Left_Parentheses||',
 ')': '||Right_Parentheses||',
 ',': '||Comma||',
 '--': '||Dash||',
 '.': '||Period||',
 ';': '||Semicolon||',
 '?': '||Question_mark||'}

## 预处理并保存所有数据
运行以下代码将预处理所有数据，并将它们保存至文件。

In [8]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# Preprocess Training, Validation, and Testing Data
helper.preprocess_and_save_data(data_dir, token_lookup, create_lookup_tables)

# preprocess
这是你遇到的第一个检点。如果你想要回到这个 notebook，或需要重新打开 notebook，你都可以从这里开始。预处理的数据都已经保存完毕。

In [77]:
text = text[81:]
token_dict = token_lookup()
for key, token in token_dict.items():#将所有的标点符号替换
        text1 = text.replace(key, ' {} '.format(token))
text_pre = text1.lower()
text_pre = text_pre.split()  #调用查找表之前需要先分割单词
vocab_to_int, int_to_vocab = create_lookup_tables(text_pre)#建立单词表
int_text = [vocab_to_int[word] for word in text_pre]#向量化输入

In [73]:
text_pre

['parentheses||',
 'into',
 'phone',
 '||right_parentheses||',
 'hold',
 'on',
 '||comma||',
 "i'll",
 'check',
 '||period||',
 '||left_parentheses||',
 'to',
 'barflies',
 '||right_parentheses||',
 'mike',
 'rotch',
 '||period||',
 'mike',
 'rotch',
 '||period||',
 'hey',
 '||comma||',
 'has',
 'anybody',
 'seen',
 'mike',
 'rotch',
 '||comma||',
 'lately',
 '||question_mark||',
 '||return||',
 'moe_szyslak:',
 '||left_parentheses||',
 'into',
 'phone',
 '||right_parentheses||',
 'listen',
 'you',
 'little',
 'puke',
 '||period||',
 'one',
 'of',
 'these',
 'days',
 "i'm",
 'gonna',
 'catch',
 'you',
 '||comma||',
 'and',
 "i'm",
 'gonna',
 'carve',
 'my',
 'name',
 'on',
 'your',
 'back',
 'with',
 'an',
 'ice',
 'pick',
 '||period||',
 '||return||',
 'moe_szyslak:',
 "what's",
 'the',
 'matter',
 'homer',
 '||question_mark||',
 "you're",
 'not',
 'your',
 'normal',
 'effervescent',
 'self',
 '||period||',
 '||return||',
 'homer_simpson:',
 'i',
 'got',
 'my',
 'problems',
 '||comma|

In [76]:
vocab_to_int['period'],vocab_to_int['||period||']

(4305, 4441)

In [78]:
int_text

[3675,
 4730,
 238,
 4022,
 1869,
 1030,
 1414,
 4441,
 1030,
 1414,
 4441,
 5513,
 5655,
 2812,
 5409,
 2531,
 1030,
 1414,
 5655,
 640,
 4495,
 5760,
 2424,
 4730,
 6412,
 448,
 1869,
 6603,
 64,
 3262,
 742,
 4441,
 5837,
 1686,
 3990,
 6439,
 4957,
 3291,
 1536,
 64,
 5655,
 429,
 4957,
 3291,
 1260,
 6047,
 6522,
 4338,
 4729,
 5764,
 5083,
 3107,
 5981,
 3139,
 4441,
 5760,
 2424,
 656,
 1136,
 5368,
 67,
 4495,
 5658,
 836,
 4729,
 5547,
 4923,
 5557,
 4441,
 5760,
 906,
 3616,
 1307,
 6047,
 3172,
 5655,
 2004,
 4441,
 813,
 3837,
 4444,
 5837,
 4441,
 5760,
 2424,
 67,
 5655,
 5513,
 5655,
 64,
 4616,
 836,
 5137,
 238,
 3226,
 4729,
 3172,
 4441,
 5760,
 4537,
 3220,
 5655,
 64,
 4616,
 1919,
 5137,
 238,
 1440,
 4729,
 5745,
 2979,
 4441,
 5760,
 5760,
 5760,
 2424,
 946,
 5655,
 6659,
 5351,
 2379,
 4441,
 5091,
 5655,
 1618,
 3282,
 2635,
 1449,
 5809,
 2219,
 4441,
 5760,
 4537,
 1932,
 3616,
 3471,
 5620,
 5655,
 3454,
 5969,
 731,
 6265,
 4441,
 4730,
 4978,
 1869,
 576

## 创建神经网络
你将通过实现下面的函数，来创造用于构建 RNN 的必要元素：

- get_inputs
- get_init\_cell
- get_embed
- build_rnn
- build_nn
- get_batches

### 检查 TensorFlow 版本并访问 GPU

In [42]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from distutils.version import LooseVersion
import warnings
import tensorflow as tf

# Check TensorFlow Version
assert LooseVersion(tf.__version__) >= LooseVersion('1.0'), 'Please use TensorFlow version 1.0 or newer'
print('TensorFlow Version: {}'.format(tf.__version__))

# Check for a GPU
if not tf.test.gpu_device_name():
    warnings.warn('No GPU found. Please use a GPU to train your neural network.')
else:
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))

TensorFlow Version: 1.7.0
Default GPU Device: /device:GPU:0


### 输入

实现函数 `get_inputs()` 来为神经网络创建 TF 占位符。它将创建下列占位符：

- 使用 [TF 占位符](https://www.tensorflow.org/api_docs/python/tf/placeholder) `name` 参量输入 "input" 文本占位符。
- Targets 占位符
- Learning Rate 占位符

返回下列元组中的占位符 `(Input, Targets, LearningRate)`

In [43]:
def get_inputs():
    """
    Create TF Placeholders for input, targets, and learning rate.
    :return: Tuple (input, targets, learning rate)
    """
    inputs = tf.placeholder(tf.int32, [None, None], name='input')
    targets = tf.placeholder(tf.int32, [None, None], name='targets')
    Learning_rate = tf.placeholder(tf.float32, name='Learning_rate')
       
    
    return (inputs, targets, Learning_rate)



"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_inputs(get_inputs)

Tests Passed


### 创建 RNN Cell 并初始化

在 [`MultiRNNCell`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell) 中堆叠一个或多个 [`BasicLSTMCells`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicLSTMCell)

- 使用 `rnn_size` 设定 RNN 大小。
- 使用 MultiRNNCell 的 [`zero_state()`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell#zero_state) 函数初始化 Cell 状态
- 使用 [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity) 为初始状态应用名称 "initial_state"
 

返回 cell 和下列元组中的初始状态 `(Cell, InitialState)`

In [44]:
def get_init_cell(batch_size, rnn_size):
    """
    Create an RNN Cell and initialize it.
    :param batch_size: Size of batches
    :param rnn_size: Size of RNNs
    :return: Tuple (cell, initialize state)
    """
    # TODO: Implement Function
    keep_prob = 0.5
    layers =2
    def build_cell(lstm_size, keep_prob):
        # Use a basic LSTM cell
        lstm = tf.contrib.rnn.BasicLSTMCell(rnn_size)
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
  
    cell  = tf.contrib.rnn.MultiRNNCell([build_cell(rnn_size, keep_prob) for _ in range(layers)])
    print(np.shape(cell))    
    initial_state = cell.zero_state(batch_size, tf.float32) 
    print('1')
    InitialState = tf.identity(initial_state, name='initial_state')
    print('2')
    return cell, InitialState

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_init_cell(get_init_cell)

()


ValueError: prefix tensor must be either a scalar or vector, but saw tensor: Tensor("Placeholder:0", dtype=int32)

### 词嵌入
使用 TensorFlow 将嵌入运用到 `input_data` 中。
返回嵌入序列。

In [45]:
def get_embed(input_data, vocab_size, embed_dim):
    """
    Create embedding for <input_data>.
    :param input_data: TF placeholder for text input.
    :param vocab_size: Number of words in vocabulary.
    :param embed_dim: Number of embedding dimensions
    :return: Embedded input.
    """
    embeddings = tf.Variable(tf.random_uniform((vocab_size, embed_dim), -1, 1))
    embed = tf.nn.embedding_lookup(embeddings, input_data)
    return embed


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_embed(get_embed)

Tests Passed


### 创建 RNN
你已经在 `get_init_cell()` 函数中创建了 RNN Cell。是时候使用这个 Cell 来创建 RNN了。

- 使用 [`tf.nn.dynamic_rnn()`](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn) 创建 RNN
- 使用 [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity) 将名称 "final_state" 应用到最终状态中


返回下列元组中的输出和最终状态`(Outputs, FinalState)`

In [146]:
def build_rnn(cell, inputs):
    """
    Create a RNN using a RNN Cell
    :param cell: RNN Cell
    :param inputs: Input text data
    :return: Tuple (Outputs, Final State)
    """
    outputs, final_state = tf.nn.dynamic_rnn(cell, inputs, dtype=tf.float32)
    final_state = tf.identity(final_state, 'final_state')
    return outputs, final_state


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_build_rnn(build_rnn)

Tests Passed


### 构建神经网络
应用你在上面实现的函数，来：

- 使用你的 `get_embed(input_data, vocab_size, embed_dim)` 函数将嵌入应用到 `input_data` 中
- 使用 `cell` 和你的 `build_rnn(cell, inputs)` 函数来创建 RNN
- 应用一个完全联通线性激活和 `vocab_size` 的分层作为输出数量。  即无输出层的激活函数

返回下列元组中的 logit 和最终状态 `Logits, FinalState`

In [147]:
def build_nn(cell, rnn_size, input_data, vocab_size, embed_dim):
    """
    Build part of the neural network
    :param cell: RNN cell
    :param rnn_size: Size of rnns
    :param input_data: Input data
    :param vocab_size: Vocabulary size
    :param embed_dim: Number of embedding dimensions
    :return: Tuple (Logits, FinalState)
    """
    embed=get_embed(input_data, vocab_size, embed_dim)
    print(np.shape(embed))
    outputs,final_state=build_rnn(cell, embed)
    print(np.shape(outputs))
    logits=tf.contrib.layers.fully_connected(outputs,vocab_size,activation_fn=None)# 
    print(np.shape(logits))
    return logits, final_state

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
#tests.test_build_nn(build_nn)


"\nDON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE\n"

### 批次

实现 `get_batches` 来使用 `int_text` 创建输入与目标批次。这些批次应为 Numpy 数组，并具有形状 `(number of batches, 2, batch size, sequence length)`。每个批次包含两个元素：

- 第一个元素为**输入**的单独批次，并具有形状 `[batch size, sequence length]`
- 第二个元素为**目标**的单独批次，并具有形状 `[batch size, sequence length]`

如果你无法在最后一个批次中填入足够数据，请放弃这个批次。

例如 `get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 2, 3)` 将返回下面这个 Numpy 数组：

```
[
  # First Batch
  [
    # Batch of Input
    [[ 1  2  3], [ 7  8  9]],
    # Batch of targets
    [[ 2  3  4], [ 8  9 10]]
  ],
 
  # Second Batch
  [
    # Batch of Input
    [[ 4  5  6], [10 11 12]],
    # Batch of targets
    [[ 5  6  7], [11 12 13]]
  ]
]
```

In [148]:
def get_batches(int_text, batch_size, seq_length):
    """
    Return batches of input and target
    :param int_text: Text with the words replaced by their ids
    :param batch_size: The size of batch
    :param seq_length: The length of sequence
    :return: Batches as a Numpy array
    """
    n_batches=len(int_text)//(batch_size*seq_length)
    result=[]
    for i in range(n_batches):#代表2个批次
        inputs=[]
        targets=[]
        for j in range(batch_size): #batch_size代表上下两端  
            idx=i*seq_length+j*seq_length*2
            inputs.append(int_text[idx:idx+seq_length])
            targets.append(int_text[idx+1:idx+seq_length+1])
        result.append([inputs,targets])
    return np.array(result)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_batches(get_batches)

Tests Passed


In [149]:
get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 2, 3)

array([[[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 2,  3,  4],
         [ 8,  9, 10]]],


       [[[ 4,  5,  6],
         [10, 11, 12]],

        [[ 5,  6,  7],
         [11, 12, 13]]]])

In [150]:
np.shape(get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 2, 3))

(2, 2, 2, 3)

## 神经网络训练
### 超参数
调整下列参数:

- 将 `num_epochs` 设置为训练次数。
- 将 `batch_size` 设置为程序组大小。
- 将 `rnn_size` 设置为 RNN 大小。
- 将 `embed_dim` 设置为嵌入大小。
- 将 `seq_length` 设置为序列长度。
- 将 `learning_rate` 设置为学习率。
- 将 `show_every_n_batches` 设置为神经网络应输出的程序组数量。

In [170]:
# Number of Epochs
num_epochs = 200
# Batch Size
batch_size = 256
# RNN Size
rnn_size = 256
# Embedding Dimension Size
embed_dim = 300
# Sequence Length
seq_length = 50
# Learning Rate
learning_rate = 0.01
# Show stats for every n number of batches
show_every_n_batches = 50

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
save_dir = './save'

### 创建图表
使用你实现的神经网络创建图表。

In [171]:
len(int_to_vocab)

6780

#### tf.contrib.seq2seq.sequence_loss可以直接计算序列的损失函数，重要参数：
#### logits：尺寸[batch_size, sequence_length, num_decoder_symbols]

#### targets：尺寸[batch_size, sequence_length]，不用做one_hot。

#### weights：[batch_size, sequence_length]，即mask，滤去padding的loss计算，使loss计算更准确。

In [172]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from tensorflow.contrib import seq2seq

train_graph = tf.Graph()
with train_graph.as_default():
    vocab_size = len(int_to_vocab)#单词表数目6780个
    input_text, targets, lr = get_inputs()
    input_data_shape = tf.shape(input_text)
    print(input_data_shape)
    cell, initial_state = get_init_cell(input_data_shape[0], rnn_size)#input_data_shape[0]即batch的维度
    logits, final_state = build_nn(cell, rnn_size, input_text, vocab_size, embed_dim)
    print(np.shape(logits))
    # Probabilities for generating words
    probs = tf.nn.softmax(logits, name='probs')
    print(np.shape(probs))
    # Loss function
    cost = seq2seq.sequence_loss(
        logits,
        targets,
        tf.ones([input_data_shape[0], input_data_shape[1]]))

    # Optimizer
    optimizer = tf.train.AdamOptimizer(lr)

    # Gradient Clipping  截断梯度  防止梯度爆炸出现
    gradients = optimizer.compute_gradients(cost)
    capped_gradients = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gradients if grad is not None]
    train_op = optimizer.apply_gradients(capped_gradients)

Tensor("Shape:0", shape=(2,), dtype=int32)
()
1
2
(?, ?, 300)
(?, ?, 256)
(?, ?, 6780)
(?, ?, 6780)
(?, ?, 6780)


## 训练
在预处理数据中训练神经网络。如果你遇到困难，请查看这个[表格](https://discussions.udacity.com/)，看看是否有人遇到了和你一样的问题。

In [173]:
#先将序列分批次
batches = get_batches(int_text, batch_size, seq_length)#batch_size=128,seq=25
np.shape(batches)#21个批次，包括了训练数据和标签，每个批次为128组，每组25个单词

(5, 2, 256, 50)

In [174]:
batches[0][0]#第一个批次的训练数据  128行 每行25个单词

array([[3675, 4730,  238, ..., 4338, 4729, 5764],
       [3220, 5655,   64, ..., 5760, 5760, 4537],
       [4495, 5760,  906, ..., 1136, 1263,  442],
       ...,
       [   1, 6639, 4441, ..., 2311,  978, 5063],
       [1426, 5655, 2635, ..., 3890, 1582, 5372],
       [  67, 5655,  946, ..., 4441, 5035, 4779]])

In [175]:
batches[0][1]#第一个批次的标签数据

array([[4730,  238, 4022, ..., 4729, 5764, 5083],
       [5655,   64, 4616, ..., 5760, 4537, 5513],
       [5760,  906,  610, ..., 1263,  442, 4017],
       ...,
       [6639, 4441, 5760, ...,  978, 5063,  238],
       [5655, 2635, 3029, ..., 1582, 5372, 5760],
       [5655,  946, 5655, ..., 5035, 4779, 3002]])

In [ ]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""


with tf.Session(graph=train_graph) as sess:
    sess.run(tf.global_variables_initializer())
    state = sess.run(initial_state, {input_text: batches[0][0]})
    for epoch_i in range(num_epochs):
        

        for batch_i, (x, y) in enumerate(batches):#即xy的维度均为128*25
            feed = {
                input_text: x,
                targets: y,
                initial_state: state,
                lr: learning_rate}
            train_loss, state, _ = sess.run([cost, final_state, train_op], feed)

            # Show every <show_every_n_batches> batches
            if (epoch_i * len(batches) + batch_i) % show_every_n_batches == 0:
                print('Epoch {:>3} Batch {:>4}/{}   train_loss = {:.3f}'.format(
                    epoch_i,
                    batch_i,
                    len(batches),
                    train_loss))

    # Save Model
    saver = tf.train.Saver()
    saver.save(sess, save_dir)
    print('Model Trained and Saved')

Epoch   0 Batch    0/5   train_loss = 8.821
Epoch  10 Batch    0/5   train_loss = 5.686


## 储存参数
储存 `seq_length` 和 `save_dir` 来生成新的电视剧剧本。

In [158]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# Save parameters for checkpoint
helper.save_params((seq_length, save_dir))

## 实现生成函数
### 获取 Tensors
使用 [`get_tensor_by_name()`](https://www.tensorflow.org/api_docs/python/tf/Graph#get_tensor_by_name)函数从 `loaded_graph` 中获取 tensor。  使用下面的名称获取 tensor：

- "input:0"
- "initial_state:0"
- "final_state:0"
- "probs:0"

返回下列元组中的 tensor `(InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)`

In [159]:
def get_tensors(loaded_graph):
    """
    Get input, initial state, final state, and probabilities tensor from <loaded_graph>
    :param loaded_graph: TensorFlow graph loaded from file
    :return: Tuple (InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)
    """
    inputs=loaded_graph.get_tensor_by_name("input:0")
    init_state=loaded_graph.get_tensor_by_name("initial_state:0")
    final_state = loaded_graph.get_tensor_by_name('final_state:0')
    probs = loaded_graph.get_tensor_by_name('probs:0')#最后预测单词的概率
    
    return inputs, init_state, final_state, probs


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_tensors(get_tensors)

Tests Passed


### 选择词汇
实现 `pick_word()` 函数来使用 `probabilities` 选择下一个词汇。

In [160]:
def pick_word(probabilities, int_to_vocab):
    """
    Pick the next word in the generated text
    :param probabilities: Probabilites of the next word
    :param int_to_vocab: Dictionary of word ids as the keys and words as the values
    :return: String of the predicted word
    """
    # TODO: Implement Function
    return  int_to_vocab[np.argmax(probabilities)]


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_pick_word(pick_word)

Tests Passed


## 生成电视剧剧本
这将为你生成一个电视剧剧本。通过设置 `gen_length` 来调整你想生成的剧本长度。

In [161]:
input_text=np.array([[2]])
np.shape(input_text)

(1, 1)

In [162]:
gen_length = 200
# homer_simpson, moe_szyslak, or Barney_Gumble
prime_word = 'moe_szyslak'#起始词

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
loaded_graph = tf.Graph()
with tf.Session(graph=loaded_graph) as sess:
    # Load saved model
    loader = tf.train.import_meta_graph(save_dir + '.meta')
    loader.restore(sess, save_dir)

    # Get Tensors from loaded model
    input_text, initial_state, final_state, probs = get_tensors(loaded_graph)

    # Sentences generation setup
    gen_sentences = [prime_word + ':']
    prev_state = sess.run(initial_state, {input_text: np.array([[2]])})#相当于batch_size=1

    # Generate sentences
    for n in range(gen_length):
        # Dynamic Input
        dyn_input = [[ vocab_to_int[word] for word in gen_sentences[-seq_length:]]]#需要写成的二维的input，即1*N,因为batch_size=1,仅有一行
        dyn_seq_length = len(dyn_input[0])#N个词 ，最大步长为25
        print(np.shape(dyn_input),'dyn_input')
        # Get Prediction
        probabilities, prev_state = sess.run(
            [probs, final_state],
            {input_text: dyn_input, initial_state: prev_state})
        print(np.shape(probabilities),'probabilities')
        pred_word = pick_word(probabilities[0][dyn_seq_length-1], int_to_vocab)
        #即取最后一个新词的预测概率，即probabilities[0][24]代表的6780个向量对应概率
      
        gen_sentences.append(pred_word)#将生成的新词加入词库
    print(gen_sentences,'gen_sentences')     
    # Remove tokens
    tv_script = ' '.join(gen_sentences)
    for key, token in token_dict.items():#加上标点符号
        #ending = ' ' if key in ['\n', '(', '"'] else ''
        tv_script = tv_script.replace(' ' + token.lower(), key)
    tv_script = tv_script.replace('\n ', '\n')
    tv_script = tv_script.replace('( ', '(')
        
    print(tv_script)

INFO:tensorflow:Restoring parameters from ./save
(1, 1) dyn_input
(1, 1, 6780) probabilities
(1, 2) dyn_input
(1, 2, 6780) probabilities
(1, 3) dyn_input
(1, 3, 6780) probabilities
(1, 4) dyn_input
(1, 4, 6780) probabilities
(1, 5) dyn_input
(1, 5, 6780) probabilities
(1, 6) dyn_input
(1, 6, 6780) probabilities
(1, 7) dyn_input
(1, 7, 6780) probabilities
(1, 8) dyn_input
(1, 8, 6780) probabilities
(1, 9) dyn_input
(1, 9, 6780) probabilities
(1, 10) dyn_input
(1, 10, 6780) probabilities
(1, 11) dyn_input
(1, 11, 6780) probabilities
(1, 12) dyn_input
(1, 12, 6780) probabilities
(1, 13) dyn_input
(1, 13, 6780) probabilities
(1, 14) dyn_input
(1, 14, 6780) probabilities
(1, 15) dyn_input
(1, 15, 6780) probabilities
(1, 16) dyn_input
(1, 16, 6780) probabilities
(1, 17) dyn_input
(1, 17, 6780) probabilities
(1, 18) dyn_input
(1, 18, 6780) probabilities
(1, 19) dyn_input
(1, 19, 6780) probabilities
(1, 20) dyn_input
(1, 20, 6780) probabilities
(1, 21) dyn_input
(1, 21, 6780) probabilities
(1,

# 这个电视剧剧本是无意义的
如果这个电视剧剧本毫无意义，那也没有关系。我们的训练文本不到一兆字节。为了获得更好的结果，你需要使用更小的词汇范围或是更多数据。幸运的是，我们的确拥有更多数据！在本项目开始之初我们也曾提过，这是[另一个数据集](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data)的子集。我们并没有让你基于所有数据进行训练，因为这将耗费大量时间。然而，你可以随意使用这些数据训练你的神经网络。当然，是在完成本项目之后。
# 提交项目
在提交项目时，请确保你在保存 notebook 前运行了所有的单元格代码。请将 notebook 文件保存为 "dlnd_tv_script_generation.ipynb"，并将它作为 HTML 文件保存在 "File" -> "Download as" 中。请将 "helper.py" 和 "problem_unittests.py" 文件一并提交。