# 矩阵计算输出 ，4*3*2的一个神经网络

In [ ]:

import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)
X   #X为默认行向量   1*4
weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))  #4*3的矩阵   从输入到隐层
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))#从隐层到输出   3*2矩阵


# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_input_to_hidden) #从输入到隐层  1*4 dot 4*3 =1*3
hidden_layer_out = sigmoid(hidden_layer_in) 

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)#1*3 dot  3*2 = 1*2  从隐层到输出层
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

In [3]:
weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_input_to_hidden #4*3矩阵    

array([[ 0.08225449, -0.12208436,  0.02088636],
       [-0.19596701, -0.1328186 ,  0.01968612],
       [ 0.07384666,  0.01713683, -0.01156483],
       [-0.03011037, -0.1478522 , -0.07198442]])

In [5]:
X = np.random.randn(4)
X  #行向量，

array([ 0.32408397, -0.38508228, -0.676922  ,  0.61167629])

In [7]:
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))
weights_hidden_to_output

array([[-0.04791742, -0.0185659 ],
       [-0.1106335 , -0.11962066],
       [ 0.08125258,  0.135624  ]])

In [9]:
hidden_layer_in = np.dot(X, weights_input_to_hidden) #从输入到隐层  1*4 dot 4*3 =1*3
hidden_layer_in

array([ 0.03371456, -0.09045747, -0.03701452])