# 反向传播3*2*1


In [43]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])#输入1*3的向量  
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6], #从输入到隐层 3*2
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])#  从隐层到输出 1*2
weights_hidden_output=weights_hidden_output.T #从隐层到输出 2*1
## Forward pass  向前传播 
hidden_layer_input = np.dot(x, weights_input_hidden) #1*3 dot 3*2=1*2 为隐层输出
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)   #1*2 dot 2*1 =1*1
output = sigmoid(output_layer_in)

## Backwards pass 误差向后传播
## TODO: Calculate output error
error = target - output    #输出层误差

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)#输出层 误差梯度  1*1

# TODO: Calculate error term for hidden layer #隐层误差梯度
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * hidden_layer_output * (1 - hidden_layer_output) 
#1*2矩阵 代表两个隐层节点的误差

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output# 1*2
xx = np.expand_dims(x, axis=1)#增加一个维度 用于计算6个权重 xx 为3*1矩阵
hidden_error_term=np.expand_dims(hidden_error_term, axis=0) #hidden_error_term为1*2
# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * np.dot(xx,hidden_error_term )# 3*1 dot 1*2 =3*2的矩阵

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)



Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]


In [40]:
xx = np.expand_dims(x, axis=0)#增加一个维度 用于计算6个权重 xx 为3*1矩阵
xx.T

array([[ 0.5],
       [ 0.1],
       [-0.2]])

In [32]:
x.T

array([ 0.5,  0.1, -0.2])

In [16]:
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output) 
output_layer_in

-0.06012438223148006

In [17]:
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output.T) 
output_layer_in

-0.06012438223148006

In [26]:
hidden_error_term

array([ 0.00070802, -0.00204471])